name: UI Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: BrowserStack
      url: https://automate.browserstack.com/dashboard/v2/public-build/YkNlcjFZam9LMmxQZzhLS0Q2Z29WWjNQczBJbUJNUDRQYjRKdU1RdHZSblhVZUVROFh5b0JlVGhKc1cwREhDenRmNVJob0RiZ2dOaVBVYi9KTFgyaWc9PS0tUlV4OVdZbEpVNjVJY3ZlaUlWQ2Fsdz09--1e361bacbef1635ac46b8c114b679d83c1be18b8

    steps:
      - name: "BrowserStack Env Setup" # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: "BrowserStack Local Tunnel Setup" # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - uses: actions/checkout@v3

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Run DevContainer
        run: |
          yarn install
          yarn devcontainer:run

      - name: Run tests
        run: |
          yarn tests:build
          yarn tests:run

      - name: "BrowserStackLocal Stop" # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
