name: Publish Userscript Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 18.x"
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint:all

      - name: Build userscript
        run: yarn userscript:release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            packages/userscript/output/*
